const CLIENT_ID =
  "YOUR CLIENT ID";
const CLEINT_SECRET = "GOCSPX-..........YOUR CLIENT SECRET";
const REDIRECT_URI =
  "4/0AfJohXnwO'''''''''''''''YOUR REDIRECT URL";
const REFRESH_TOKEN =
  "1//04HMmZtEmPs........YOUR REFRESH TOKRN";
module.exports = { CLIENT_ID, CLEINT_SECRET, REDIRECT_URI, REFRESH_TOKEN };
